# Generated by Django 3.2.9 on 2021-11-08 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodes_1', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_2', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_3', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_4', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_5', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_6', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_7', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_8', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_9', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_10', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_11', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_12', models.FileField(blank=True, null=True, upload_to='series/')),
                ('episodes_13', models.FileField(blank=True, null=True, upload_to='series/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('video', models.FileField(upload_to='videos/')),
                ('poster', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('documentary', 'DOCUMENTARY'), ('martial arts', 'MARTIAL ARTS'), ('historical', 'HISTORICAL'), ('adventure', 'ADVENTURE'), ('animation', 'ANIMATION'), ('thriller', 'THRILLER'), ('romance', 'ROMANCE'), ('fantasy', 'FANTASY'), ('horror', 'HORROR'), ('action', 'ACTION'), ('comedy', 'COMEDY'), ('sci-fi', 'SCI-FI'), ('drama', 'DRAMA')], max_length=15)),
                ('status', models.CharField(choices=[('recently added', 'RECENTLY ADDED'), ('most watched', 'MOST WATCHED'), ('top rated', 'TOP RATED'), ('trending', 'TRENDING'), ('popular', 'POPULAR'), ('upcoming', 'UPCOMING')], max_length=21)),
                ('release_year', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('poster', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('documentary', 'DOCUMENTARY'), ('martial arts', 'MARTIAL ARTS'), ('historical', 'HISTORICAL'), ('adventure', 'ADVENTURE'), ('animation', 'ANIMATION'), ('thriller', 'THRILLER'), ('romance', 'ROMANCE'), ('fantasy', 'FANTASY'), ('horror', 'HORROR'), ('action', 'ACTION'), ('comedy', 'COMEDY'), ('sci-fi', 'SCI-FI'), ('drama', 'DRAMA')], max_length=15)),
                ('status', models.CharField(choices=[('recently added', 'RECENTLY ADDED'), ('most watched', 'MOST WATCHED'), ('top rated', 'TOP RATED'), ('trending', 'TRENDING'), ('popular', 'POPULAR'), ('upcoming', 'UPCOMING')], max_length=21)),
                ('release_year', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('episodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_episodes', to='broadapp.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar/deafult.png', upload_to='avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
